# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AlterField(
            model_name='event',
            name='from_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('NO', 'not important'), ('SH', 'should be done'), ('MI', 'midly important'), ('I', 'important'), ('VI', 'very important'), ('EI', 'extremely important')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.IntegerField(),
        ),
    ]
