# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import pyday_calendar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_calendar', '0002_auto_20160702_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_time',
            field=models.IntegerField(validators=[pyday_calendar.validators.validate_range(1, 24)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.IntegerField(validators=[pyday_calendar.validators.validate_range(1, 24)]),
        ),
    ]
