# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_alarms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alarms',
            new_name='Alarm',
        ),
    ]
