# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_alarms', '0002_auto_20160705_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='caption',
            new_name='message',
        ),
    ]
