# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_alarms', '0003_auto_20160705_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
