# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('picture', models.FileField(upload_to='pictures/')),
            ],
        ),
    ]
