# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_social_network', '0002_auto_20160503_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pydayuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 3, 10, 45, 59, 33304, tzinfo=utc)),
        ),
    ]
