# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:12
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_social_network', '0003_auto_20160502_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pydayuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 18, 12, 32, 135312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pydayuser',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
