# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pyday_social_network', '0003_auto_20160702_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pydayuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 3, 21, 51, 20, 85379, tzinfo=utc)),
        ),
    ]
